version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_streamflix
    restart: always
    environment:
      POSTGRES_DB: streamflix_db
      POSTGRES_USER: streamflix_user
      POSTGRES_PASSWORD: streamflix_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
